### ISSUE TITLE
Install is successful but error messages might lead the impatient to cancel the script prematurely

### ISSUE THREAD

**Issue by marcredhat** [kxr/ocp4_setup_upi_kvm#10]
Deploying 4.5.0-rc6 alongside an existing 4.4.10 on the same KVM host worked great.
./NEW_ocp4_setup_upi_kvm.sh --setup-dir /root/ocp4_setup_ocp45 --ocp-version 4.5.0-rc.6 --cluster-name ocp45.

However, during the install, "an unknown error has occurred: MultipleErr" messages occured (please see below).
which might lead the impatient to cancel the script prematurely....

We might want to add messages advising patience / ignoring these errors.

====> Waiting for clusterversion:
.......
  --> Approving CSR: certificatesigningrequest.certificates.k8s.io/csr-zffgk approved
  --> Working towards 4.5.0-rc.6: 75% complete
  --> Unable to apply 4.5.0-rc.6: an unknown error has occurred: MultipleErr ...
  --> Unable to apply 4.5.0-rc.6: an unknown error has occurred: MultipleErr ...
  --> Working towards 4.5.0-rc.6: 62% complete
  --> Working towards 4.5.0-rc.6: 62% complete
  --> Unable to apply 4.5.0-rc.6: an unknown error has occurred: MultipleErr ...
  --> Patching image registry to use EmptyDir: config.imageregistry.operator.openshift.io/cluster patched
  --> Patching ingress controller to run router pods on master nodes: ingresscontroller.operator.openshift.io/default patched
  --> Working towards 4.5.0-rc.6: 99% complete

**Comment by kxr** [comment]
@marcredhat I actually had the same idea. However I was reluctant add a warning since there is already so much text floating around. How about we add this to the README?

**Comment by marcredhat** [comment]
Yes, I think adding this to the README would work well.

**Comment by kxr** [comment]
Added note in README: [661a9c4](https://github.com/kxr/ocp4_setup_upi_kvm/commit/661a9c4de88829331fae48b138bc43142df97b5c)
