### ISSUE TITLE
Local storage

### ISSUE THREAD

**Issue by marcredhat** [kxr/ocp4_setup_upi_kvm#11]
I used to be able to deploy Local Storage as per https://github.com/marcredhat/upi/blob/master/ocp44-local-storage.adoc

Currently, I can get only small PVs s.a. the ones below.

[root@dell-r730-001 ~]# oc get pv
NAME                CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS   REASON   AGE
local-pv-4ad711f5   384Mi      RWO            Delete           Available           marcsc                  29m
local-pv-64df8c7e   384Mi      RWO            Delete           Available           marcsc                  29m
local-pv-90a727a8   384Mi      RWO            Delete           Available           marcsc                  29m
local-pv-939e5fe4   384Mi      RWO            Delete           Available           marcsc                  29m
local-pv-e5a876b9   384Mi      RWO            Delete           Available           marcsc                  29m

I can only use /dev/vda1 as /dev/vda4 is not recognized by the Local Storage Operator.

[core@worker-2 ~]$ lsblk -a
NAME                         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
vda                          252:0    0  1000G  0 disk
├─vda1                       252:1    0   384M  0 part /boot
├─vda2                       252:2    0   127M  0 part /boot/efi
├─vda3                       252:3    0     1M  0 part
└─vda4                       252:4    0 999.5G  0 part
  └─coreos-luks-root-nocrypt 253:0    0 999.5G  0 dm   /sysroot

[core@worker-2 ~]$ lsblk -no FSTYPE /dev/vda4
crypto_LUKS
xfs

Increasing the disk size for workers does not help 
as all the available space goes to /dev/vda4, 
which is not recognized by the Local Storage Operator.

**Comment by kxr** [comment]
@marcredhat What I would suggest is that you setup a cluster with 0 or minimal number of workers. Once the cluster is up, you can then add additional nodes (see [adding-nodes](https://github.com/kxr/ocp4_setup_upi_kvm/blob/master/README.md#adding-nodes)) and use the `--add-disk` to add additional disks. These disks will be added as sdb, sdc and so on.

**Comment by marcredhat** [comment]
Great suggestion, thanks @kxr !
