### ISSUE TITLE
~/.kube/config is not created

### ISSUE THREAD

**Issue by Cheny-chen** [kxr/ocp4_setup_upi_kvm#15]
Fedora 32 
Linux kernel 5.8.9-200.fc32.x86_64
Red Hat OpenShit Version = 4.5.9
Red Hat CoreOS Version = 4.5.6

Install command
`./ocp4_setup_upi_kvm.sh --cluster-name ocp4 --ocp-version 4.5.latest --pull-secret pull-secret --vm-dir /mnt/vms2/images`

#################################
#################################

====> Waiting for clusterversion: 
  --> Working towards 4.5.9: 62% complete
  --> Patching ingress controller to run router pods on master nodes: ingresscontroller.operator.openshift.io/default patched
  --> **Unable to apply 4.5.9: an unknown error has occurred: MultipleErrors**
  --> Patching image registry to use EmptyDir: config.imageregistry.operator.openshift.io/cluster patched
  --> Working towards 4.5.9: 82% complete, waiting on authentication, cluste ...
  --> Working towards 4.5.9: 86% complete
  --> Working towards 4.5.9: 87% complete
  **--> Unable to apply 4.5.9: the cluster operator operator-lifecycle-manager ...
  --> Unable to apply 4.5.9: the cluster operator operator-lifecycle-manager ...**

######################################################
######################################################
          time taken = 78 minutes

INFO Waiting up to 30m0s for the cluster at https://api.ocp4.local:6443 to initialize... 
INFO Waiting up to 10m0s for the openshift-console route to be created... 
INFO Install complete!                            
INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/root/ocp4_setup_ocp4/install_dir/auth/kubeconfig' 
INFO Access the OpenShift web-console here: https://console-openshift-console.apps.ocp4.local 
INFO Login to the console with user: "kubeadmin", and password: "JtLWu-Cnrj4-NsmCN-8YGch" 
INFO Time elapsed: 0s                             

```
[root@localhost ~]# oc login -u kubeamdin -p JtLWu-Cnrj4-NsmCN-8YGch https://api.ocp4.local:6443
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

Login failed (401 Unauthorized)
Verify you have provided correct credentials.
[root@localhost ~]# oc get nodes
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.

```
[root@localhost ~]# ls .kube/config
ls: cannot access '.kube/config': No such file or directory
[root@localhost ~]# kubectl version --client
error: no configuration has been provided
[root@localhost ~]# kubectl version --client=true
error: no configuration has been provided

**Comment by kxr** [comment]
Check the kubeconfig and kubeadmin-password file in `<setup-dir>/install_dir/auth/`.
You can copy it to the default location `cp /<setup-dir>/install_dir/auth/kubeconfig /root/.kube/config`

**Comment by Cheny-chen** [comment]
> Check the kubeconfig and kubeadmin-password file in `<setup-dir>/install_dir/auth/`.
> You can copy it to the default location `cp /<setup-dir>/install_dir/auth/kubeconfig /root/.kube/config`



Thank you very much. It works.  However, 2 workers is not on the list.


[root@localhost ~]# oc login -u kubeadmin -p ELTqR-mDxtD-2cqbG-DtLEz https://api.ocp4.local:6443
Login successful.

You have access to 57 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
[root@localhost ~]# oc get nodes
NAME                  STATUS    ROLES           AGE       VERSION
master-1.ocp4.local   Ready     master,worker   50m       v1.18.3+2cf11e2
master-2.ocp4.local   Ready     master,worker   50m       v1.18.3+2cf11e2
master-3.ocp4.local   Ready     master,worker   50m       v1.18.3+2cf11e2
