### ISSUE TITLE
GET result: Internal Server Error on installation of worker node

### ISSUE THREAD

**Issue by Cheny-chen** [kxr/ocp4_setup_upi_kvm#16]
Fedora 32
Linux kernel 5.8.9-200.fc32.x86_64
Red Hat OpenShit Version = 4.5.9
Red Hat CoreOS Version = 4.5.6

Install command
```./ocp4_setup_upi_kvm.sh --cluster-name ocp4 --ocp-version 4.5.latest --pull-secret pull-secret --vm-dir /mnt/vms2/images```

During installation processing, it never check worker1 and worker2.
Two workers console keep showing repeatedly
```
Get result: Internal Server Error
GET https://api-int.ocp4.local:22623/config/worker
```

The boostrap console show repeatedly
```
 SELinux: mount invalid. Same superblock, different security settings for (dev mqueue, type mqueue)
```

If check installation processing log, It never asked for workers if workers Ready or not.

``` 
 --> Node master-1.ocp4.local NotReady
  --> Node master-2.ocp4.local NotReady
  --> Node master-3.ocp4.local NotReady
............
  --> Node master-1.ocp4.local Ready
  --> Node master-2.ocp4.local Ready
  --> master-3.ocp4.local Ready
```

[root@localhost ~]# oc login -u kubeadmin -p ELTqR-mDxtD-2cqbG-DtLEz https://api.ocp4.local:6443
Login successful.

You have access to 57 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
[root@localhost ~]# oc get nodes
NAME                  STATUS    ROLES           AGE       VERSION
master-1.ocp4.local   Ready     master,worker   50m       v1.18.3+2cf11e2
master-2.ocp4.local   Ready     master,worker   50m       v1.18.3+2cf11e2
master-3.ocp4.local   Ready     master,worker   50m       v1.18.3+2cf11e2

**Comment by kxr** [comment]
Yeah I think in the recent versions I have noticed that sometimes worker nodes are not properly added to the cluster by the installer.

Check the `Pending` CSR requests by running `oc get csr` and approve any pending requests by `oc adm certificate approve <csr-name>`. You will have to do it twice for each node.

**Comment by Cheny-chen** [comment]
> Yeah I think in the recent versions I have noticed that sometimes worker nodes are not properly added to the cluster by the installer.
> 
> Check the `Pending` CSR requests by running `oc get csr` and approve any pending requests by `oc adm certificate approve <csr-name>`. You will have to do it twice for each node.

Thank you so much.  It works. :+1:

**Comment by kxr** [comment]
@Cheny-chen Hello I have added the logic in the script to wait for the CSR approvals and worker nodes to get ready before the script finishes.
