### ISSUE TITLE
allow users to specify and clean up unneeded operators

### ISSUE THREAD

**Issue by marcredhat** [kxr/ocp4_setup_upi_kvm#19]
Hi,

What would be the best way to allow users to 
specify unneeded operators and
clean them up as done by CodeReady Containers at https://github.com/code-ready/snc/blob/master/snc.sh#L414-L456?

Thanks,
Marc

**Comment by kxr** [comment]
Sorry, for replying so late. I would consider operator cleanup to be day2 operation. The objective of the script is to bring up a cluster with minimal hassle. Once the cluster is up, user can do what ever they like.
