### ISSUE TITLE
stuck with "Waiting for SSH access on Boostrap VM..."

### ISSUE THREAD

**Issue by rcdelacruz** [kxr/ocp4_setup_upi_kvm#23]
I like your script, but i don't know why i am stuck with "Waiting for SSH access on Boostrap VM..."

**Comment by kxr** [comment]
@rcdelacruz This is because the script is not able get ssh access to the bootstrap vm. You can check this manually to investigate this further. When the script is stuck, open a new shell session and run `ssh -i </path/to/sshkey> core@bootstrap.<cluster-name>.<base-domain>`. This will give you a hint of whats wrong. Use the `sshkey` that is generated by the script in the `setup-dir` (default: /root/ocp4_setup_\<cluster-name\>).

**Comment by rcdelacruz** [comment]
@kxr I tried to ssh into the bootstrap vm and i got this: ```ssh: connect to host bootstrap.homelab.local port 22: No route to host``` 
Here's my ```etc/hosts```:
```192.168.122.19 lb.homelab.local api.homelab.local api-int.homelab.local
192.168.122.110 bootstrap.homelab.local
192.168.122.100 master-1.homelab.local etcd-0.homelab.local
192.168.122.193 master-2.homelab.local etcd-1.homelab.local
192.168.122.216 master-3.homelab.local etcd-2.homelab.local
192.168.122.122 worker-1.homelab.local
192.168.122.125 worker-2.homelab.local
```

bootstrap is unreachable
```
PING 192.168.122.110 (192.168.122.110) 56(84) bytes of data.
From 192.168.122.1 icmp_seq=1 Destination Host Unreachable
```

Am i missing something?

Thanks

**Comment by kxr** [comment]
@rcdelacruz That is strange. Can you check the status of bootstrap VM at this stage? See if its running and if it is, see the console of the bootstrap vm to check if something is wrong there.

BTW, how much RAM and CPU does the host have (on which you are trying to create the openshift cluster)?

**Comment by rcdelacruz** [comment]
@kxr Ok i will further investigate.

I am using an 8-core Ryzen 7 with 32GB of memory

**Comment by kxr** [comment]
32 GB is quite on the edge. Though I have seen cluster getting deployed on a host with 32 GB memory, just make sure you have the maximum memory available for the cluster VMs. Also I would recommend to deploy the cluster with just the master nodes (set `--workers 0`) because of low resources.
