### ISSUE TITLE
Cannot pass the SRV test step

### ISSUE THREAD

**Issue by anderotxoa** [kxr/ocp4_setup_upi_kvm#24]
All I get is the following message:
##################
##################

====> Adding test records in /etc/hosts: ok
====> Testing DNS forward record from LB: ok
====> Testing DNS reverse record from LB: ok
====> Adding test SRV record in dnsmasq: ok
====> Testing SRV record from LB: 

[ERROR] ERROR: Testing SRV record failed

May be I am doing something wrong? (most probably but cannot find what)

**Comment by kxr** [comment]
@marcredhat Lets see. So the script is basically checking if it adds a dns record on the host/hypervisor, will that dns record work, inside the VM? So adding a record to /etc/hosts works fine. But if we add an srv record, it is not detected inside the VM. Now the thing about srv record is that it is added in your dnsmasq.d directory which ever one you selected using `--dns-dir`. By default its set to "/etc/NetworkManager/dnsmasq.d". 

So double check:
- Host/hypervisor is using dnsmasq (either via NetworkManager or direct dnsmasq service).
- First entry in `/etc/resolv.conf` is pointing to localhost/127.0.0.1 (this should be there if the system is using dnsmasq)
- You are specifying the `--dns-dir` correctly and pointing it to the correct dnsmasq

**Comment by anderotxoa** [comment]
Hi
Thanks for your tips. I may have managed to make it work. 
Yes, the mess was in the DNS for sure.
I started using the system dnsmasq instead of the NetwrkManager one and used --dns-dir to point to the /etc/dmsmasq.d directory.
It now is installing quite well...
