### ISSUE TITLE
infinite loop operator

### ISSUE THREAD

**Issue by jesusdevop** [kxr/ocp4_setup_upi_kvm#29]
Hello, the script enters a loop, I attach an example, it has reached operator 25, in a process that has lasted hours and I have aborted:

--> Image Downloaded: quay.io/openshift-release-dev/ocp-v4.0-art-dev-68f1a254ca71
  --> Image Downloaded: quay.io/openshift-release-dev/ocp-v4.0-art-dev-c13ef4e8416a
  --> Phase Completed: ingress-operator-bootstrap
  --> Phase Completed: kube-controller-manager-bootstrap
  --> Phase Completed: kube-scheduler-bootstrap
  --> Image Downloaded: quay.io/openshift-release-dev/ocp-v4.0-art-dev-9af9a3146176
  --> Image Downloaded: quay.io/openshift-release-dev/ocp-v4.0-art-dev-99bafb4c397f
  --> Image Downloaded: quay.io/openshift-release-dev/ocp-v4.0-art-dev-fee670561aab
  --> Phase Completed: cco-bootstrap
  --> Phase Completed: mco-bootstrap
  --> Container: cloud-credential-operator 0 Exited
  --> Container: machine-config-server 0 Running
  --> Container: machine-config-controller 0 Exited
  --> Image Downloaded: quay.io/openshift-release-dev/ocp-v4.0-art-dev-3acc45bb0d5d
  --> Container: kube-apiserver-insecure-readyz 0 Running
  --> Container: kube-apiserver 0 Running
  --> Container: kube-scheduler 0 Running
  --> Container: kube-controller-manager 0 Exited
  --> Container: setup 0 Exited
  --> Container: cluster-version-operator 0 Running
  --> Container: cloud-credential-operator 1 Exited
  ==> Kubernetes API is Up
  --> Container: kube-controller-manager 1 Running
  --> Container: cloud-credential-operator 2 Exited
  --> Container: cloud-credential-operator 3 Created
  --> Container: cloud-credential-operator 3 Running
  --> (bootkube.service is active, Kube API is Up)
  --> (bootkube.service is active, Kube API is Up)

**Comment by kxr** [comment]
If possible, can you share:
- The command used to create the cluster.
- Complete output of the script.
- `oc get clusterversion,co,nodes`; `oc get pods -A` (see previous comment on how to use oc)
- Specs of the host where you are running this script. Is it a VM or physical host?

**Comment by jesusdevop** [comment]
It does not finish installing and does not recognize the oc command

**Comment by jesusdevop** [comment]
The installation still continues


--> Container: kube-apiserver 9 Running
  --> Container: kube-apiserver 8 Exited
  --> Container: kube-controller-manager 5 Running
  --> (bootkube.service is active, Kube API is Up)
  --> (bootkube.service is active, Kube API is Up)
  --> (bootkube.service is active, Kube API is Up)
  --> (bootkube.service is active, Kube API is Up)
  --> (bootkube.service is active, Kube API is Up)
  --> Container: kube-apiserver 11 Running
  --> Container: kube-apiserver 10 Exited
  --> Container: kube-controller-manager 4 Running
  --> (bootkube.service is active, Kube API is Up)
  --> (bootkube.service is active, Kube API is Up)
  --> (bootkube.service is active, Kube API is Up)
  --> (bootkube.service is active, Kube API is Up)
  --> Container: cloud-credential-operator 5 Exited
  --> Container: kube-apiserver 12 Running
  --> Container: kube-apiserver 11 Exited
  --> (bootkube.service is active, Kube API is Up)
  --> (bootkube.service is active, Kube API is Up)
  --> (bootkube.service is active, Kube API is Up)
  --> (bootkube.service is active, Kube API is Up)
  --> Container: kube-apiserver 12 Exited
  --> Container: kube-apiserver 13 Running
  --> (bootkube.service is active, Kube API is Up)
  --> (bootkube.service is active, Kube API is Up)
  --> (bootkube.service is active, Kube API is Up)
  --> Container: kube-controller-manager 6 Exited
  --> Container: kube-controller-manager 7 Running

**Comment by jesusdevop** [comment]
I have tried different versions of Openshift 4.2,4.3,4.5 and I always have the same result.

**Comment by jesusdevop** [comment]
[root@localhost auth]# cat kubeconfig
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lJRjVhdXpOS2N0dWN3RFFZSktvWklodmNOQVFFTEJRQXdQakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1TZ3dKZ1lEVlFRREV4OXJkV0psTFdGd2FYTmxjblpsY2kxc2IyTmhiR2h2YzNRdApjMmxuYm1WeU1CNFhEVEl4TVRBeE5qRTNORFF5TTFvWERUTXhNVEF4TkRFM05EUXlNMW93UGpFU01CQUdBMVVFCkN4TUpiM0JsYm5Ob2FXWjBNU2d3SmdZRFZRUURFeDlyZFdKbExXRndhWE5sY25abGNpMXNiMk5oYkdodmMzUXQKYzJsbmJtVnlNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdqZGxva0Z2MjhmbgpLT2o2VlFGZFJNWUJqeCswdkdJenZ2WFZoR2d2eEtRd3RKZUJJaGhneEx1YXo0czRHQ3VRWjZ4UnVrQ25QbGIvClVpempJZFBBWTg3QjNUOVdMQTIyaEZpSVlQVktEM3F4Q3lTMWFSYXdJL2szV011M1dpSVJxdThVcG1OVklqbVYKQ0pZc0REaUpHY3M3b3QremVTL3BYbFV5cEx4UG4zWDNReTVIOWRPNW9IeWJHeXV4SVZMbmtFdk5qaXVKNlZXQQpZblRSWG1lMVNyaFdpLy9aZEpBNFVzZmQzeVc0OFZ2QlhVZjNYMmJ2UEFDTHBTL0lTSE1vMlVVUDVHUTJaU3R4Cm5EdVI2RDFNRTFPZnhUZmxyZGhIbCtaRFJYR1FaSzM4VnNsRUVmSE9RTS9BbE5udEozT2RpaFNnaDVUblFPTHQKUEs5c25ZOWdnd0lEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVUE1McWlMRkMxK04zTm1WTk9xS1J5VzNUQkM4d0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBRXlscm5SMERGdlowRHBhalMwTzcxYWJWdjJwSzI3NlQyQlRPRE9IcmJ0OEJ3KzdydXRmUUZPNktrKzUKTEMwVFF3QUpweHpjWHpPaXI1YzFqMElyblFVS1VNY0c3Zzh4a3NSWHQzMVc1ZmxoUFJOYmdQT0J0SnRzaW9qYQpVQ3NXUmM2eVVmdWFNUnZRK1hhTzlUZlA2eXh5MEpoNGpsMmxrVkJrVHZJODFHd2J1QXBINTJaR1EvRitlcWZnCnZjTE5XQUxST1JFNUFCc2cvdlR6WTVuRTQ5dnA2dk5rd1pXdWtkQ3AyNlZpd0hrZlk1ZnJWbDM4L0JKS1ZMZG4KYmhHb3lzOUpIT0I2bEQxTnFybGNOUllhMXp0OFFMcXlHNzZzTE8xMVJRZnNQUWN5M2JrcDJ4VkpvdEtLMWtlRApScHNTUTFoUUFWRm1lS2hKYUh6SFZCUCtLd3c9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURURENDQWpTZ0F3SUJBZ0lJSG1mQ2dwZHBFbWd3RFFZSktvWklodmNOQVFFTEJRQXdSREVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1TNHdMQVlEVlFRREV5VnJkV0psTFdGd2FYTmxjblpsY2kxelpYSjJhV05sTFc1bApkSGR2Y21zdGMybG5ibVZ5TUI0WERUSXhNVEF4TmpFM05EUXlNMW9YRFRNeE1UQXhOREUzTkRReU0xb3dSREVTCk1CQUdBMVVFQ3hNSmIzQmxibk5vYVdaME1TNHdMQVlEVlFRREV5VnJkV0psTFdGd2FYTmxjblpsY2kxelpYSjIKYVdObExXNWxkSGR2Y21zdGMybG5ibVZ5TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQwpBUUVBM2s3b0M0a1FkVzhWYVZFN1BpUUhhR2F3UHpxQjBlNlI5NS80ekg2M0tWRDgya0N4WGxHVll0UW82NysrCmw1cFdpa1M1bHF6dWRtajBtRkZoRGpBbGlnd3pWQmNlV2dndGJhaVBHUTZvU3RXRVl5S3BISysrTTlzMjFwQkwKM2lNTGZTS3RMTGtLNjFnQnlBWjN6YnRCS3FZNjhXVTJKVlVzVS9DcTBsdDhzd2o4Yy9YbkoyVktyT2tuaDRIUwozdFV4MVVtR2RxWXhXYWhxeWxCLzBIdmxpNXMyRmIrMGNYa3Rma0lpdmRxMzFHZGhpelBiN0c1R0V1bTZFSXdYClN6MnpxZ2psenhQbnhpTHJEa00rSC9JcGMwN3Z1b2pjSmhGSFVySjdzVUpRVXBYaG9nREQxUkNqQ1lVODY3aVkKR2hNRHJyVzEvTFF3WndpTGJ1YU4zLzVYVFFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRApWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTVGdi9jT2x2emttczJXZXVGVVBFOW94QmpxVXdEUVlKCktvWklodmNOQVFFTEJRQURnZ0VCQUE4TitWYjFrNXU3S3ZvQWFuRVhYS09ldUJPOFVCdWl6OUxsdzlBcW1iS0wKWE5UTTd0ZStTU3diLzNoSUw3UUN4WFRiSFlzNVc5MEhHajFYMGZ3T3M4cW9WTTd1VzU2ZUR2a1ZCL1NWbUllegpKZGl4NmdtTWVUVFBPcnBNSWxxUXlHR0FPZER1UHVNalk5Q2VCY2JndnBmZG9IVmUyK2xWNmpRTGNUNW5vam85CkJSQ0JBMDNhYlZqMFhmelNWQVJKWjhjai93Umk1djZkUUJsS2w0TXpyRDJBTC92T3Y0YmQxa1EvZ0xNUmd6NDgKNEp0Mmt2VXlkRkRwUmUwRlM2M1dnUHM0Q0hwcHBkbXpBZ200bFVZTG5aSGpYajc0dEdDdUxPUzBiWndQU0VmdQpPbTQ1Q1ROZDhyRTltN29Vc2IxcVl0RUMxU0lMNDhmVFI2eGVBeXh2cnF3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlETWpDQ0FocWdBd0lCQWdJSUg5RkwxcHVYSjlZd0RRWUpLb1pJaHZjTkFRRUxCUUF3TnpFU01CQUdBMVVFCkN4TUpiM0JsYm5Ob2FXWjBNU0V3SHdZRFZRUURFeGhyZFdKbExXRndhWE5sY25abGNpMXNZaTF6YVdkdVpYSXcKSGhjTk1qRXhNREUyTVRjME5ESXpXaGNOTXpFeE1ERTBNVGMwTkRJeldqQTNNUkl3RUFZRFZRUUxFd2x2Y0dWdQpjMmhwWm5ReElUQWZCZ05WQkFNVEdHdDFZbVV0WVhCcGMyVnlkbVZ5TFd4aUxYTnBaMjVsY2pDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU9jL0R1WmRvMHBVM0VxUU1FV3FBYXhLcExFN2VFY3oKNWYxM0VZWnJvN2ViNG0zbE5tSk5wWHBoVnNjM0VxUW05dnBEcVFEc3l5Y3F3bEZjTC83TjZLRnFlRDdJT2pZegppejM3T0tNYkZKcEUxUlhzL21odVpnRHNiQkNOUDVSRlNxaXpqYXlYck9qc25CMXVsYVFDNWZMRTU0d2RDT3NICkE3QUlPNGgrYUxZdFVwcHNSbkE3UHVMTmxYWmhoWFc4aHpnZEV3SW9JS3h6RTdTQU9oYzl2YWtqY2tqYUxvdVYKNUxsdFJyWElkZjFZOXc5cUV5NjRBRy9tOHBHYmpRZ0p2MmRKcVBRcmNvN2hCN0Jqa3hUQUNSazdFZEtBUWJaaQo5ZXBxc1pHMFN6M2pqKzNEenR3dU9KcnhtMTdqMG1DaUx5Qko0SVZnQThOQVdNSWYxQmgvRTBVQ0F3RUFBYU5DCk1FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZMNXkKMHhUVXZqb1RtWllleHFCNU5SUndoL09rTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBczZjTU44WjRuN0Z5SApMTGRaUlFXdEtSQ1QvZ2NDMU5xM1kxVU82UEhSeEk1T0lzNW9RQ1VaMGxsRmx1M2xOYzRROEVmcFI5K2dlTmRDClJDZnZGQ3VyL0YvM2htMzg5TGJuekh3ZWtucVczMWNhNmFQOC9NMmp4UVpnU2JNa3hFWWJrWkw1L0JhSUppSjAKdVJ1eXJrZ0dBUWpocGtmU0JDaFZKa2JxUElma3N6NitralJXbGRLQUtTOHB4YURJMjQ1U3gxL1VzMGhCa041Vgp3dTB0RHduclB0ZTRwUXFCU3doNTZLSm9zeWx5MS9HOWJ2VERBNGJpT0Z6bTZqTktNajZnQzY0NkZvNHlMaUJDCnYrUm9DcW9pd09vUmxBZU0vNWNIdWJjSElFaUhKYnVYTVpXOHFqM3NueS8wUXdUVzRFeUs1RFNURkxkRC9tNUEKME1hRUlJV0sKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://api.ocp4.local:6443
  name: ocp4
contexts:
- context:
    cluster: ocp4
    user: admin
  name: admin
current-context: admin
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaekNDQWsrZ0F3SUJBZ0lJTlBFUmxPSFZ2ek13RFFZSktvWklodmNOQVFFTEJRQXdOakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1TQXdIZ1lEVlFRREV4ZGhaRzFwYmkxcmRXSmxZMjl1Wm1sbkxYTnBaMjVsY2pBZQpGdzB5TVRFd01UWXhOelEwTWpOYUZ3MHpNVEV3TVRReE56UTBNak5hTURBeEZ6QVZCZ05WQkFvVERuTjVjM1JsCmJUcHRZWE4wWlhKek1SVXdFd1lEVlFRREV3eHplWE4wWlcwNllXUnRhVzR3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNyd1BmcFJLaGtxNHhXalc1cGNyNkRNenpoc3RCaCtqZzQ0ckhQYXJmMgpCRDM2OTU2cGlTQ3B2TVVWQ25SWkpmdkFVak02R01UMXdCZFJlL1VxN3lDcVU2aWlNWnAybzBSTGxlLys3d2E5CjB6cUp6UVh6NjBTalJ2ejU4SnBacWNjcm4rRis0ZFNPNWswdjVvMVNqSHpYR1lScXl4VWpDOWNXZ29IYTVhdG8Kc2dIODE4OFNKVGZHZnlIY1ZZbDIyOVlWUk5jTHZIZGVpdWswMmplTWc2VS95eVhBVXlLS01aOEpGVXVSZ1A4aQpHd2VZSVRXTjhOUHA3QjloRHlRZXIrTll2eG1vTmxFOVloOHp0SWlqNkdXc3l0WWVXS1NSSVp0ZnV4dmIvdiswCkUwR1hBSXFYVkFVQ3VZNEdpM1ZYM1YzblllKzhuRDYreTI5dzdmcFJtbW9KQWdNQkFBR2pmekI5TUE0R0ExVWQKRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEVlIwVApBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVOaGZtSnYrY20ybXJQc2x3RFRXNWJnaURUTHd3SHdZRFZSMGpCQmd3CkZvQVV5cDJlMEFvV3k1Zk0yMlRUZGx6MTFTWEZ2Nkl3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdjTk5HWGEKMTdER2hrTENPR2RWWklrbFd1bVNjcTZLZ2dmTVNBK01ERXNIK21Bbm1ZSUMwZlFmL0RDYUNuY2F2SWZoc0dSSwp4VkJuV09ma1J6eFYvczdRVGdpZ2lzN1NmSmJNc2V4Y2c2WXU0WFozMEpUeVBrcVEzU0g3S21jOXltQ2FlU1BuClRRQWRFN0RWUjNPNlN1VnhaaFQ5emp0OFRaUDdUUkJZZDlhNThVa3lmSThQV0wzRExBbENCQWJ2QVc0LytZTlMKZWJxQ2YyREowNzg5SWU3Tm5tRDJhNU9oUDBHYngzdG00ZmJWVW5zU1VyK1RMOU55ZVFGbjFxTlJhNW1Lc2c0eAo2RVVoa0JGSks1QWFtdm16THJrd0lxZExNM3JRbzZjTkN6QTlVZVZpVENCdXpOR2dyT3pZSjcxQWR1Nk9QSFpDClJOT0d6MTdYOHNDQ2lGQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcThEMzZVU29aS3VNVm8xdWFYSytnek04NGJMUVlmbzRPT0t4ejJxMzlnUTkrdmVlCnFZa2dxYnpGRlFwMFdTWDd3Rkl6T2hqRTljQVhVWHYxS3U4Z3FsT29vakdhZHFORVM1WHYvdThHdmRNNmljMEYKOCt0RW8wYjgrZkNhV2FuSEs1L2hmdUhVanVaTkwrYU5Vb3g4MXhtRWFzc1ZJd3ZYRm9LQjJ1V3JhTElCL05mUApFaVUzeG44aDNGV0pkdHZXRlVUWEM3eDNYb3JwTk5vM2pJT2xQOHNsd0ZNaWlqR2ZDUlZMa1lEL0loc0htQ0UxCmpmRFQ2ZXdmWVE4a0hxL2pXTDhacURaUlBXSWZNN1NJbytobHJNcldIbGlra1NHYlg3c2IyLzcvdEJOQmx3Q0sKbDFRRkFybU9Cb3QxVjkxZDUySHZ2SncrdnN0dmNPMzZVWnBxQ1FJREFRQUJBb0lCQVFDZEE4OWdJSlUxV3lMego2VjM3NXB0R0JDeHZSUEo5NzZ0QVRmWXg0YVVGc29FYkV3Nm9mS1V3cDFNZzFpcmhhUGtLcTlzTERLUGE2bDRtCjd3U0YySkJyUmduUEpUdkpvNTZHM3k3RlI2MUpFbmJjaldNWXg0YzdJV1daOVJ5V1JjREFIK3ljKzBVLzBralUKTnBnUjFEODR3YW90bXpUYWtqTnk3NkpaQkVlOGNDZUFHZTllS3A4QTVhTnh3bWlacGtvZC9oTjJ5dlZMTnVTbwp0c1liUHhFQ1hIVnBrNjZPWTRaM2hXL3FpVUhDcGNKdzFsYStOcWxZMUZPZ1RpMnlWVlF3Y2VPY3l1dU8yQ09YCkFvVXBtSUlQdjJKdjZJNE1uU1pQQ3VPM1pSQjhtbXY4dU9pRUpOajJ6TG9RUVJOR1dsbjVGWXJkd2hBUFJHYVkKUUFpSmtnU1JBb0dCQU1VSHhXcUsvRHdRWThYR1YrRGd5bGZSa3p4ZnEwZytOanJCakk1U3lIbVU4Ym9XOGh1QQppMjFMekpkNkRxYW11Z3lSM1lZMnpjYzJMZnA4SXRMRURhbnNVVUZTbDdZV3RiUElKTnJQdHBxbkVlVzU5aDJYCllVVkdWL3VmeDVyRkNtRkdMU2pPYUF1QVE4MmZwTkt1b3ZVSzM3a29sT2hXL2hjRGp4L3hEWHRkQW9HQkFOOG8KaVY5d1JUbmtZUlV6b2VBOFY4ekYxZlhFRHJTWTBnZmFhZ3JLdmlmOXF3NkRXYUtHMzZYWFptKzhCUDB2SWJRUAovN2o2UTdldjZWQ3ZJT3pkOEVxaXR5aVk1ZFF5OVpQa1h5YkJNY3BOck81MnZLSXdVSjVQU2R5TUx4YWRFOGxlCnJjUldsQk8vR2d4SXB4bVY5cUxvQlpVaXFWQmdBOWVUaDExdGNxcWRBb0dCQUxPMTR0cks2a1hlclNJM1J2QlcKR0RrQmJzb2llSmZzSm9wdy8wTFJQd21tVU5UckdPajgxaTlhYzhHMkVxYnVhOFFMUjRLamVnMjUzVFliQTZnNgpLanhTejhwRkN4dUttekRmM0wyM3QxWllESHI4b3Y5YWs5NGJ5eVEzR0ZpU1lHVlpITmViYkVzUk1zYmFWZnZVClRjNHpuTnZGcUF4RFRINnhRRnBpQTJvQkFvR0FUbVgvWFBna1dlSlIrUkRhbmR5Vk8rdUU3NEtoWi9FSVdKbnoKQnplUzlwbTNyckdXbS9LbVA2MGMzOFErUEhTQ2NxL3NOeUExQ2lOUzVIV2lLNVVOQml1RURVOHA3eEs0RSt6MwpRTFkrdDhQeUxSU3AwSkVJd1pVNWJiSVNHTysyTTloL1U2clcrdGo0WGJob2ZDU2pNVGd5UGVLZmVRMUNURW9ZCkZFcVBMa0VDZ1lBSmxIOVQ4OVBiQ1FGSU9VSmNNZEJLaEZlT3BneWtIck8wRGFrbmhMOUo2Q3dRUjMxSWhsSzIKRFVyR1NzTDYyVlBUeTFTWG1FR3ZBQlFsd2pTaXE2L04vaURRMi9OZCs3NzAvMnNJakJmNC9BOFVCMDl4YVV0ZQpRbldRL1RWVTl0NU83cndHcDJzWGIxcEt3dVRONUI0NlZFekpvRi9STmxKdVEwT3ZLRmF1T1E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
[root@localhost auth]#

**Comment by jesusdevop** [comment]
I observe that it does not create .kube / config I have followed issue # 15 now the output is:

[root@localhost auth]# oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version             False       True          13m     Unable to apply 4.2.36: an unknown error has occurred
[root@localhost auth]# oc get pods -A
NAMESPACE                                    NAME                                                     READY   STATUS      RESTARTS   AGE
openshift-apiserver-operator                 openshift-apiserver-operator-855d65f5dd-tm2gs            0/1     Pending     0          8m16s
openshift-cloud-credential-operator          cloud-credential-operator-7c857c95c-trl9c                0/1     Pending     0          8m16s
openshift-cluster-machine-approver           machine-approver-d5dd4b565-sj2ft                         0/1     Pending     0          8m16s
openshift-cluster-version                    cluster-version-operator-55f9dffd86-7hr5j                1/1     Running     0          8m16s
openshift-controller-manager-operator        openshift-controller-manager-operator-69479fc684-qlnpt   0/1     Pending     0          8m16s
openshift-controller-manager                 controller-manager-tqppx                                 1/1     Running     1          8m16s
openshift-dns-operator                       dns-operator-647bf4d6c8-r9jdd                            0/1     Pending     0          8m16s
openshift-dns                                dns-default-8z8rb                                        2/2     Running     0          10m
openshift-insights                           insights-operator-5f69749bfc-c5tmf                       0/1     Pending     0          8m16s
openshift-kube-apiserver-operator            kube-apiserver-operator-565598c94d-pg52m                 0/1     Pending     0          8m16s
openshift-kube-controller-manager-operator   kube-controller-manager-operator-7bfbf8c6b-t9w5k         0/1     Pending     0          8m11s
openshift-kube-controller-manager            installer-3-localhost                                    0/1     Completed   0          8m15s
openshift-kube-controller-manager            kube-controller-manager-localhost                        2/2     Running     0          7m51s
openshift-kube-scheduler-operator            openshift-kube-scheduler-operator-bcc5fdb-rsww8          0/1     Pending     0          8m16s
openshift-machine-api                        machine-api-operator-5d64f65dd-l69jm                     0/1     Pending     0          8m14s
openshift-machine-config-operator            etcd-quorum-guard-79bcfb468b-8fdbw                       1/1     Running     0          9m39s
openshift-machine-config-operator            etcd-quorum-guard-79bcfb468b-cdpb8                       0/1     Pending     0          9m39s
openshift-machine-config-operator            etcd-quorum-guard-79bcfb468b-qmnn9                       0/1     Pending     0          9m39s
openshift-machine-config-operator            machine-config-controller-848c565968-sbgj4               0/1     Pending     0          8m12s
openshift-machine-config-operator            machine-config-daemon-t8dmc                              1/1     Running     0          10m
openshift-machine-config-operator            machine-config-operator-6977d6df5f-hrfnr                 0/1     Pending     0          8m13s
openshift-machine-config-operator            machine-config-server-96fsw                              1/1     Running     0          9m51s
openshift-multus                             multus-admission-controller-vtmz8                        1/1     Running     0          11m
openshift-multus                             multus-jdfsm                                             1/1     Running     0          13m
openshift-network-operator                   network-operator-7fd8bbd68c-qpnnr                        0/1     Pending     0          8m16s
openshift-sdn                                ovs-wx45q                                                1/1     Running     0          12m
openshift-sdn                                sdn-controller-kb6l9                                     1/1     Running     0          12m
openshift-sdn                                sdn-xqm8g                                                1/1     Running     0          12m
openshift-service-ca-operator                service-ca-operator-6c77dc59c8-72d9g                     0/1     Pending     0          8m11s
openshift-service-ca                         apiservice-cabundle-injector-78f4797b95-7fxrd            0/1     Pending     0          8m11s
openshift-service-ca                         configmap-cabundle-injector-78667ddcf-c944q              0/1     Pending     0          8m11s
openshift-service-ca                         service-serving-cert-signer-56f4599fcc-lwngp             0/1     Pending     0          8m16s
